"""Initial migration

Revision ID: 413e52c9ced1
Revises: 
Create Date: 2026-07-09 09:10:03.521888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '413e52c9ced1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ai_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('tool_used', sa.String(length=100), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_logs_id'), 'ai_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_logs_session_id'), 'ai_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_ai_logs_user_id'), 'ai_logs', ['user_id'], unique=False)
    op.create_table('hcps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hospital', sa.String(length=255), nullable=True),
    sa.Column('speciality', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hcp_name_hospital', 'hcps', ['name', 'hospital'], unique=False)
    op.create_index(op.f('ix_hcps_hospital'), 'hcps', ['hospital'], unique=False)
    op.create_index(op.f('ix_hcps_id'), 'hcps', ['id'], unique=False)
    op.create_index(op.f('ix_hcps_location'), 'hcps', ['location'], unique=False)
    op.create_index(op.f('ix_hcps_name'), 'hcps', ['name'], unique=False)
    op.create_index(op.f('ix_hcps_speciality'), 'hcps', ['speciality'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hcp_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('visit_type', sa.String(length=100), nullable=False),
    sa.Column('products_discussed', sa.JSON(), nullable=True),
    sa.Column('samples_given', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hcp_id'], ['hcps.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_date'), 'interactions', ['date'], unique=False)
    op.create_index(op.f('ix_interactions_hcp_id'), 'interactions', ['hcp_id'], unique=False)
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('hcp_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('suggested_products', sa.JSON(), nullable=True),
    sa.Column('suggested_questions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['hcp_id'], ['hcps.id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_date'), 'followups', ['date'], unique=False)
    op.create_index(op.f('ix_followups_hcp_id'), 'followups', ['hcp_id'], unique=False)
    op.create_index(op.f('ix_followups_id'), 'followups', ['id'], unique=False)
    op.create_index(op.f('ix_followups_interaction_id'), 'followups', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_followups_user_id'), 'followups', ['user_id'], unique=False)
    op.create_table('interaction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_history_id'), 'interaction_history', ['id'], unique=False)
    op.create_index(op.f('ix_interaction_history_interaction_id'), 'interaction_history', ['interaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_history_interaction_id'), table_name='interaction_history')
    op.drop_index(op.f('ix_interaction_history_id'), table_name='interaction_history')
    op.drop_table('interaction_history')
    op.drop_index(op.f('ix_followups_user_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_interaction_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_hcp_id'), table_name='followups')
    op.drop_index(op.f('ix_followups_date'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_hcp_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_date'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_hcps_speciality'), table_name='hcps')
    op.drop_index(op.f('ix_hcps_name'), table_name='hcps')
    op.drop_index(op.f('ix_hcps_location'), table_name='hcps')
    op.drop_index(op.f('ix_hcps_id'), table_name='hcps')
    op.drop_index(op.f('ix_hcps_hospital'), table_name='hcps')
    op.drop_index('ix_hcp_name_hospital', table_name='hcps')
    op.drop_table('hcps')
    op.drop_index(op.f('ix_ai_logs_user_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_session_id'), table_name='ai_logs')
    op.drop_index(op.f('ix_ai_logs_id'), table_name='ai_logs')
    op.drop_table('ai_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
